

import sys
from PDFWriter import PDFWriter

pw = PDFWriter('Generated-ASCII-Table.pdf')
pw.setFont('Courier', 12)
#pw.setFont('Helvetica', 12)
pw.setHeader('Generated ASCII Table - for characters 32 to 126 decimal')
pw.setFooter('Generated by xtopdf: http://slid.es/vasudevram/xtopdf')

pw.writeLine('DEC'.rjust(10) + 'HEX'.rjust(10) + 'CHAR'.rjust(10))
pw.writeLine(' ' * 30)
for i in range(32, 127):
    dec_i = str(i)
    hex_i = hex(i)
    char_i = chr(i)
    pw.writeLine(dec_i.rjust(10) + hex_i.rjust(10) + char_i.rjust(10))
    pw.writeLine(' ' * 30)

pw.close()



